---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: crawler-ui
  labels:
    app: crawler
    component: ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: ui
  template:
    metadata:
      name: crawler-ui
      labels:
        app: crawler
        component: ui
    spec:
      containers:
      - image: mad72/crawler-ui:latest
        name: ui
        env:
        - name: MONGO
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_APP
          value: ui.py
